global:
  scrape_interval: 15s

scrape_configs:
  - job_name: minimal-agent
    authorization:
      type: Bearer
      credentials_file: /etc/prometheus/data/metrics-token
    static_configs:
      - targets: ["agent:8000"]
